<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise-封装 | 11 - catch 方法与异常穿透</title>
    <script src="./1Promise自定义封装-catch方法-异常穿透与值传递.js"></script>
</head>
<body>
    <script>
        // 实例化对象
        let p = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve('OK');
            }, 1000)
        })

        // let res = p.catch(reason => {
        //     console.warn(reason);
        // })
        // console.log(res);

        // 值传递
        p.then()
        // p.then(value => {
        //     console.log(111);
        // })
        .then(value => {
            console.log(222);
        }).then(value => {
            console.log(333);
        }).catch(reason => {
            console.warn(reason);
        })
    </script>
</body>
</html>